**Setting environment**

In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
pd.__version__ #Checking panda version

os.getcwd()
#if you want to change work directory use below command
#os.chdir('E:\Documents\_Dropbox\Dropbox\Playground\Jupyter\notebook\Thesis')

'C:\\My\\_DropboxSync\\Dropbox\\Playground\\Jupyter\\notebook\\Thesis'

**Loading data file**

In [26]:
#Loading data file
barley = pd.read_csv('./data/barley_01.csv', sep=',', header=0, index_col=0)

**Explorering data**

In [27]:
#Explorering data
barley.head()

,1,2,3,4,5,6,7,8,9,10,...,141,142,143,144,145,146,147,148,149,150
*dRpg1,B,A,A,A,A,B,A,A,A,B,...,B,B,B,B,B,B,A,A,B,B
*iPgd1A,B,A,A,A,A,B,A,A,A,B,...,B,B,B,B,B,B,A,A,B,B
*BCD129,B,A,A,A,A,B,A,A,A,B,...,B,B,B,B,B,B,A,A,B,~
*iEst5,B,A,A,A,A,B,A,A,A,B,...,B,B,B,B,B,B,A,A,B,B
*Prx1A,B,A,A,A,A,B,A,A,A,B,...,B,B,B,B,B,B,A,A,B,B

In [28]:
barley.info()

<class 'pandas.core.frame.DataFrame'>
Index: 127 entries, *dRpg1 to *MWG632
Columns: 150 entries, 1 to 150
dtypes: object(150)
memory usage: 149.8+ KB

In [29]:
barley[[0]]

          1
*dRpg1    B
*iPgd1A   B
*BCD129   B
*iEst5    B
*Prx1A    B
*aHis3A   B
*ABG380   B
*MWG836   B
*Brz      B
*MWG003   B
*MWG511   B
*MWG626   A
*VAtp57A  A
*MWG571D  A
*MWG889B  A
*ABC310B  A
*PSR129   A
*ABC253   B
*ABG608   B
*WG380A   B
*MWG635B  B
*MWG844   A
*ABG058   A
*WG516    A
*MWG655A  A
*MWG520A  A
*Pox      A
*BCD351B  A
*ABG716   A
*BCD111   A
...      ..
*MWG658   A
*ABG713   A
*ABA306B  A
*Act8B    A
*MWG502   A
*ABC483   A
*MWG920A  A
*ABG705A  A
*Dor5     A
*MWG635A  A
*BCD410B  A
*CDO348B  A
*ksuA1B   B
*MWG522   B
*mSrh     B
*ABC717   B
*MWG914   B
*Ugp3     ~
*RZ404    B
*MWG781   B
*CDO504   B
*ABG712   B
*TubA3    B
*MWG740   B
*BCD298   B
*ABC622   A
*ABG463   A
*ABG057B  A
*ABC309   A
*MWG632   ~

[127 rows x 1 columns]

In [30]:
barley.dtypes

1      object
2      object
3      object
4      object
5      object
6      object
7      object
8      object
9      object
10     object
11     object
12     object
13     object
14     object
15     object
16     object
17     object
18     object
19     object
20     object
21     object
22     object
23     object
24     object
25     object
26     object
27     object
28     object
29     object
30     object
        ...
121    object
122    object
123    object
124    object
125    object
126    object
127    object
128    object
129    object
130    object
131    object
132    object
133    object
134    object
135    object
136    object
137    object
138    object
139    object
140    object
141    object
142    object
143    object
144    object
145    object
146    object
147    object
148    object
149    object
150    object
dtype: object

In [31]:
barley.describe()

,1,2,3,4,5,6,7,8,9,10,...,141,142,143,144,145,146,147,148,149,150
count,127,127,127,127,127,127,127,127,127,127,...,127,127,127,127,127,127,127,127,127,127
unique,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
top,A,B,A,B,B,A,B,A,A,B,...,B,A,A,A,B,B,B,A,A,B
freq,73,81,70,64,67,60,69,60,70,80,...,69,61,66,62,76,73,66,78,64,65

In [32]:
barley[:2]

,1,2,3,4,5,6,7,8,9,10,...,141,142,143,144,145,146,147,148,149,150
*dRpg1,B,A,A,A,A,B,A,A,A,B,...,B,B,B,B,B,B,A,A,B,B
*iPgd1A,B,A,A,A,A,B,A,A,A,B,...,B,B,B,B,B,B,A,A,B,B

In [33]:
barley['1']

*dRpg1      B
*iPgd1A     B
*BCD129     B
*iEst5      B
*Prx1A      B
*aHis3A     B
*ABG380     B
*MWG836     B
*Brz        B
*MWG003     B
*MWG511     B
*MWG626     A
*VAtp57A    A
*MWG571D    A
*MWG889B    A
*ABC310B    A
*PSR129     A
*ABC253     B
*ABG608     B
*WG380A     B
*MWG635B    B
*MWG844     A
*ABG058     A
*WG516      A
*MWG655A    A
*MWG520A    A
*Pox        A
*BCD351B    A
*ABG716     A
*BCD111     A
           ..
*MWG658     A
*ABG713     A
*ABA306B    A
*Act8B      A
*MWG502     A
*ABC483     A
*MWG920A    A
*ABG705A    A
*Dor5       A
*MWG635A    A
*BCD410B    A
*CDO348B    A
*ksuA1B     B
*MWG522     B
*mSrh       B
*ABC717     B
*MWG914     B
*Ugp3       ~
*RZ404      B
*MWG781     B
*CDO504     B
*ABG712     B
*TubA3      B
*MWG740     B
*BCD298     B
*ABC622     A
*ABG463     A
*ABG057B    A
*ABC309     A
*MWG632     ~
Name: 1, dtype: object

In [34]:
barley.iloc[0:5, 0:5] #Data frame indexing

         1  2  3  4  5
*dRpg1   B  A  A  A  A
*iPgd1A  B  A  A  A  A
*BCD129  B  A  A  A  A
*iEst5   B  A  A  A  A
*Prx1A   B  A  A  A  A

**Preprocessing**

In [35]:
#Transposing
barley_t = barley.transpose()
print(barley_t.iloc[0:5, 0:5])
print(barley_t.info())

  *dRpg1 *iPgd1A *BCD129 *iEst5 *Prx1A
1      B       B       B      B      B
2      A       A       A      A      A
3      A       A       A      A      A
4      A       A       A      A      A
5      A       A       A      A      A
<class 'pandas.core.frame.DataFrame'>
Index: 150 entries, 1 to 150
Columns: 127 entries, *dRpg1 to *MWG632
dtypes: object(127)
memory usage: 150.0+ KB
None

In [36]:
#Test code(dropping)
test = barley_t.iloc[0:5, 0:5]; test
test.drop(labels=test.columns[[1]], axis=1) #dropping column
test.drop(labels=test.index[[1-1]]) #dropping row

  *dRpg1 *iPgd1A *BCD129 *iEst5 *Prx1A
2      A       A       A      A      A
3      A       A       A      A      A
4      A       A       A      A      A
5      A       A       A      A      A

In [37]:
# 39, 96, 116, 103 th DH lines removed for marker mapping(146 marker mappings)
# and also 33 th DH line should be removed for QTL analysis(145 lines)
barley_td = barley_t.drop(labels=barley_t.index[[39-1, 96-1, 116-1, 103-1, 33-1]])
barley_td.info()

<class 'pandas.core.frame.DataFrame'>
Index: 145 entries, 1 to 150
Columns: 127 entries, *dRpg1 to *MWG632
dtypes: object(127)
memory usage: 145.0+ KB

In [42]:
barley_td[90:100]

,*dRpg1,*iPgd1A,*BCD129,*iEst5,*Prx1A,*aHis3A,*ABG380,*MWG836,*Brz,*MWG003,...,*CDO504,*ABG712,*TubA3,*MWG740,*BCD298,*ABC622,*ABG463,*ABG057B,*ABC309,*MWG632
93,A,A,A,A,A,A,B,B,B,A,...,A,A,~,~,A,A,A,A,A,A
94,A,A,A,A,B,B,B,B,B,A,...,B,A,~,A,A,A,B,B,B,B
95,A,A,A,A,A,A,A,A,A,B,...,A,A,~,B,B,B,B,B,B,B
97,B,B,B,B,B,B,B,B,B,B,...,A,A,A,A,A,A,A,A,A,A
98,B,B,B,B,B,~,B,B,B,B,...,A,A,A,A,A,A,A,A,A,A
99,B,B,B,B,B,B,B,B,B,B,...,A,A,A,B,B,B,B,B,B,B
100,A,A,A,B,B,B,B,B,B,B,...,B,B,B,A,A,A,B,B,B,B
101,A,A,A,A,A,A,B,B,B,A,...,A,A,A,B,B,B,B,B,B,B
102,A,A,A,A,~,A,A,A,A,A,...,B,B,B,B,B,A,A,A,A,A
104,A,A,A,A,A,A,A,A,A,A,...,A,A,A,A,A,B,B,B,B,B

NameError: name 'pip' is not defined